### ISSUE TITLE
[R0.60b] Nox Yvviar dialogue has inconsistent spelling

### ISSUE THREAD

**Issue by chris-torrence** [6502-workshop/NA#29]
It looks like Nox Yvviar's dialogue has 2 different spellings for Vha'ak Oblicae:
<img width="665" alt="screen shot 2018-11-11 at 10 56 29 pm" src="https://user-images.githubusercontent.com/5461379/48329309-5fb93b80-e605-11e8-853b-e08782b171e5.png">

**Comment by 6502-workshop** [comment]
Thanks!

MY NOTES
-------------

Reproduced in current build (commit fb8afb306a3fb7d42746d4fb135615e0308ebb22)

The ASCII is correct in the .TLK file. The problem appears to be with the text window parser

**Comment by 6502-workshop** [comment]
fixed. thanks!

MY NOTES
------------

The text was correct in the .TLK file. It appears that the cross assembler was not translating the apostrophe character to the correct ASCII value. Oddly, it's only happening with the cult name and not even every time the cult name is used.

For that reason I suspect it's a cross assembler bug rather than a control character I wasn't aware of. 

The fix was to hard code the ASCII value for the apostrophe character in the .TLK file.
