### ISSUE TITLE
Crashing bug with white rectangle mob

### ISSUE THREAD

**Issue by chris-torrence** [6502-workshop/NA#9]
I encountered the terrible white square of doom, and then the game crashed when I tried to fight it...
<img width="1092" alt="screen shot 2018-11-03 at 3 19 04 pm" src="https://user-images.githubusercontent.com/5461379/47957478-19683a80-df7c-11e8-8cce-40f6398ae21c.png">
<img width="1123" alt="screen shot 2018-11-03 at 3 20 29 pm" src="https://user-images.githubusercontent.com/5461379/47957479-1ec58500-df7c-11e8-9f24-32c6c09647a4.png">

**Comment by 6502-workshop** [comment]
LOL! That's weird. The white square of doom is not something that should be there. I don't see it when I put a pristine copy of R0.59.

Could you try the following, if you haven't already, and see if the white square goes away?

1) reboot the disk image

2) transfer your saved game to a pristine R0.59 image so we can see if your files on image got corrupted. Not by something you did, but a bug in the game.

3) If none of the above work, email me your disk image. 

I don't want to attach images here but if you'd like me to resend you one by email just let me know. 

Thanks!

**Comment by chris-torrence** [comment]
Here’s the “pristine” disk image with my saved game - still shows the white square and crashes. To see it, just start the game and move the party down and to the left, over the bridge.
-Chris


On Nov 3, 2018, at 4:56 PM, 6502-workshop <notifications@github.com> wrote:

LOL! That's weird. The white square of doom is not something that should be there. I don't see it when I put a pristine copy of R0.59.

Could you try the following, if you haven't already, and see if the white square goes away?

reboot the disk image

transfer your saved game to a pristine R0.59 image so we can see if your files on image got corrupted. Not by something you did, but a bug in the game.

If none of the above work, email me your disk image.

I don't want to attach images here but if you'd like me to resend you one by email just let me know.

Thanks!

**Comment by 6502-workshop** [comment]
Chris, how did you sent the disk image? I don't see a link to it in the github issue and don't see an email  with it. Sorry if I missed it!

**Comment by 6502-workshop** [comment]
Chris, thanks! I received the disk image and found the bug in the mob spawning table. It will be fixed in the next release.

 In the meantime, while running R0.59, crossing the cow barrier greatly increases the chance of triggering this bug. In fact, try to keep the cow barrier out of site. If you see it, don't go any closer. The bug is in the "default" mob spawn table and once your player is outside of the developed area there are no spawning records so the default is used. 

And, since you're current image now has an invincible white mob, here is a patch to get rid of it which you can apply with the Virtual2 memory editor (or other emulator). Wait until the white square is on screen then apply the patch. 

$BD28: 00 00 00 00

If that doesn't work just let me know. And, if it doesn't work, reboot without saving the game right away.

**Comment by chris-torrence** [comment]
Yep, patching seemed to work - thanks!
